FROM node:22-alpine AS setup 
EXPOSE 80

FROM setup as build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build 

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

CMD [ "nginx", "-g", "daemon off;"]
